project_name: bsc-erigon

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ amd64 ]
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    tags: [ nosqlite, noboltdb, nosilkworm, netgo ]
    ldflags: -s -w

  - id: darwin-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb, nosilkworm, netgo ]
    ldflags: -s -w

  - id: linux-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    tags: [ nosqlite, noboltdb, nosilkworm, netgo ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    tags: [ nosqlite, noboltdb, nosilkworm, netgo ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: windows-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    tags: [ nosqlite, noboltdb, nosilkworm, netgo ]
    ldflags: -s -w


snapshot:
  name_template: "{{ .Tag }}.next"