name: ci-pr

on:
  push:
    branches:
      - devel

jobs:
  ci:
    # tmp fix
    uses: node-real/github-workflows/.github/workflows/ci-pr.yml@fix-arm64
    secrets: inherit
    with:
      ci-lint-skip: true
      ci-test-skip: true
